package com.hahaen.ledger.transaction.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.hahaen.ledger.account.entity.LedgerAccount;
import com.hahaen.ledger.account.mapper.LedgerAccountMapper;
import com.hahaen.ledger.book.service.BookService;
import com.hahaen.ledger.common.exception.BusinessException;
import com.hahaen.ledger.common.security.AuditSupport;
import com.hahaen.ledger.transaction.dto.*;
import com.hahaen.ledger.transaction.entity.*;
import com.hahaen.ledger.transaction.mapper.*;
import com.hahaen.ledger.transaction.vo.TransactionDetailVO;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.util.*;

@Service @RequiredArgsConstructor
public class TransactionService {
    private final LedgerTransactionMapper transactionMapper; private final TransactionRefundMapper refundMapper; private final LedgerAccountMapper accountMapper; private final BookService bookService;
    private long bookId() { return bookService.current().getId(); }
    private LedgerAccount account(long id, String kind) { LedgerAccount a = accountMapper.selectOne(new LambdaQueryWrapper<LedgerAccount>().eq(LedgerAccount::getId,id).eq(LedgerAccount::getBookId,bookId()).eq(LedgerAccount::getStatus,"ACTIVE").last("for update")); if (a == null || (kind != null && !kind.equals(a.getKind()))) throw new BusinessException("ACCOUNT_NOT_AVAILABLE", "账户不可用"); return a; }
    private void change(LedgerAccount a, long delta) { long next = a.getKind().equals("FUND") ? a.getBalanceCents() + delta : a.getBalanceCents() + delta; if (a.getKind().equals("FUND") && next < 0) throw new BusinessException("BALANCE_NOT_ENOUGH", "账户余额不足"); if (a.getKind().equals("CREDIT") && next < 0) throw new BusinessException("DEBT_INVALID", "信贷账户欠款不能小于 0"); if (a.getKind().equals("CREDIT") && next > a.getCreditLimitCents()) throw new BusinessException("CREDIT_LIMIT_EXCEEDED", "欠款不能超过总额度"); a.setBalanceCents(next); a.setUpdatedAt(LocalDateTime.now()); accountMapper.updateById(a); }
    private void validateAmount(long amount) { if (amount <= 0 || amount > 99999999999L) throw new BusinessException("INVALID_AMOUNT", "金额必须在 ¥0.01～¥999,999,999.99 之间"); }
    private String normalizedType(String type) { if (type == null || type.isBlank()) throw new BusinessException("INVALID_TRANSACTION_TYPE", "账单类型不合法"); return type.toUpperCase(Locale.ROOT); }
    @Transactional public LedgerTransaction create(TransactionRequest r) {
        validateAmount(r.amountCents()); String type = normalizedType(r.type()); if (!Set.of("EXPENSE","INCOME","TRANSFER").contains(type)) throw new BusinessException("INVALID_TRANSACTION_TYPE", "账单类型不合法");
        long id = bookId(); if (r.idempotencyKey()!=null && transactionMapper.selectOne(new LambdaQueryWrapper<LedgerTransaction>().eq(LedgerTransaction::getBookId,id).eq(LedgerTransaction::getIdempotencyKey,r.idempotencyKey())) != null) return transactionMapper.selectOne(new LambdaQueryWrapper<LedgerTransaction>().eq(LedgerTransaction::getBookId,id).eq(LedgerTransaction::getIdempotencyKey,r.idempotencyKey()));
        LedgerAccount account = null, from = null, to = null;
        if (type.equals("TRANSFER")) { if (r.fromAccountId() == null || r.toAccountId() == null) throw new BusinessException("ACCOUNT_REQUIRED", "请选择转出和转入账户"); if (Objects.equals(r.fromAccountId(), r.toAccountId())) throw new BusinessException("SAME_ACCOUNT", "转出账户和转入账户不能相同"); from=account(r.fromAccountId(),"FUND"); to=account(r.toAccountId(),"FUND"); change(from,-r.amountCents()); change(to,r.amountCents()); }
        else { if (r.accountId() == null) throw new BusinessException("ACCOUNT_REQUIRED", "请选择资金账户"); account=account(r.accountId(),"FUND"); change(account,type.equals("EXPENSE") ? -r.amountCents() : r.amountCents()); }
        LedgerTransaction t = new LedgerTransaction(); t.setBookId(id); t.setType(type); t.setAmountCents(r.amountCents()); t.setAccountId(account==null?null:account.getId()); t.setFromAccountId(from==null?null:from.getId()); t.setToAccountId(to==null?null:to.getId()); t.setOccurredAt(r.occurredAt()); t.setNote(r.note()); t.setStatus("ACTIVE"); t.setIdempotencyKey(r.idempotencyKey()); t.setCreatedAt(LocalDateTime.now()); t.setUpdatedAt(LocalDateTime.now()); transactionMapper.insert(t); return t;
    }
    @Transactional public LedgerTransaction update(long id, TransactionRequest r) {
        LedgerTransaction t = require(id); String type = normalizedType(r.type()); validateAmount(r.amountCents());
        if (!type.equals(t.getType())) throw new BusinessException("TRANSACTION_TYPE_IMMUTABLE", "编辑时不能修改账单类型");
        if (refundMapper.selectCount(new LambdaQueryWrapper<TransactionRefund>().eq(TransactionRefund::getTransactionId,id).eq(TransactionRefund::getStatus,"ACTIVE")) > 0) throw new BusinessException("REFUNDED_TRANSACTION_IMMUTABLE", "已有退款的账单不能直接编辑");
        if (type.equals("TRANSFER")) { if (r.fromAccountId() == null || r.toAccountId() == null) throw new BusinessException("ACCOUNT_REQUIRED", "请选择转出和转入账户"); if (Objects.equals(r.fromAccountId(),r.toAccountId())) throw new BusinessException("SAME_ACCOUNT", "转出账户和转入账户不能相同"); change(account(t.getFromAccountId(),"FUND"),t.getAmountCents()); change(account(t.getToAccountId(),"FUND"),-t.getAmountCents()); var from=account(r.fromAccountId(),"FUND"); var to=account(r.toAccountId(),"FUND"); change(from,-r.amountCents()); change(to,r.amountCents()); t.setAccountId(null); t.setFromAccountId(from.getId()); t.setToAccountId(to.getId()); }
        else { if (r.accountId() == null) throw new BusinessException("ACCOUNT_REQUIRED", "请选择资金账户"); change(account(t.getAccountId(),"FUND"),type.equals("EXPENSE")?t.getAmountCents():-t.getAmountCents()); var a=account(r.accountId(),"FUND"); change(a,type.equals("EXPENSE")?-r.amountCents():r.amountCents()); t.setAccountId(a.getId()); t.setFromAccountId(null); t.setToAccountId(null); }
        t.setAmountCents(r.amountCents()); t.setOccurredAt(r.occurredAt()); t.setNote(r.note()); t.setUpdatedAt(LocalDateTime.now()); transactionMapper.updateById(t); return t;
    }
    public List<LedgerTransaction> list(LocalDate from, LocalDate to, Long accountId, String type) { LambdaQueryWrapper<LedgerTransaction> q=new LambdaQueryWrapper<LedgerTransaction>().eq(LedgerTransaction::getBookId,bookId()).eq(LedgerTransaction::getStatus,"ACTIVE").ge(from!=null,LedgerTransaction::getOccurredAt,from==null?null:from.atStartOfDay()).lt(to!=null,LedgerTransaction::getOccurredAt,to==null?null:to.plusDays(1).atStartOfDay()).eq(type!=null&&!type.isBlank(),LedgerTransaction::getType,type).orderByDesc(LedgerTransaction::getOccurredAt); if(accountId!=null) q.and(w->w.eq(LedgerTransaction::getAccountId,accountId).or().eq(LedgerTransaction::getFromAccountId,accountId).or().eq(LedgerTransaction::getToAccountId,accountId)); return transactionMapper.selectList(q); }
    public TransactionDetailVO detail(long id) { LedgerTransaction t=require(id); List<TransactionRefund> rs=refundMapper.selectList(new LambdaQueryWrapper<TransactionRefund>().eq(TransactionRefund::getTransactionId,id).eq(TransactionRefund::getStatus,"ACTIVE").orderByDesc(TransactionRefund::getRefundedAt)); long total=rs.stream().mapToLong(TransactionRefund::getAmountCents).sum(); return new TransactionDetailVO(t,total,t.getAmountCents()-total,rs); }
    public LedgerTransaction require(long id) { LedgerTransaction t=transactionMapper.selectOne(new LambdaQueryWrapper<LedgerTransaction>().eq(LedgerTransaction::getId,id).eq(LedgerTransaction::getBookId,bookId()).eq(LedgerTransaction::getStatus,"ACTIVE")); if(t==null) throw new BusinessException("TRANSACTION_NOT_FOUND","账单不存在"); return t; }
    @Transactional public void delete(long id) { LedgerTransaction t=require(id); if(t.getType().equals("TRANSFER")){change(account(t.getFromAccountId(),"FUND"),t.getAmountCents());change(account(t.getToAccountId(),"FUND"),-t.getAmountCents());} else { long refunded=refundMapper.selectList(new LambdaQueryWrapper<TransactionRefund>().eq(TransactionRefund::getTransactionId,id).eq(TransactionRefund::getStatus,"ACTIVE")).stream().mapToLong(TransactionRefund::getAmountCents).sum(); long effective=t.getAmountCents()-refunded; change(account(t.getAccountId(),"FUND"),t.getType().equals("EXPENSE")?effective:-effective); } t.setStatus("DELETED"); AuditSupport.markDeleted(t); transactionMapper.updateById(t); }
    @Transactional public TransactionRefund refund(long id, RefundRequest r) { LedgerTransaction t=require(id); if(!Set.of("EXPENSE","INCOME").contains(t.getType())) throw new BusinessException("REFUND_UNSUPPORTED","转账和还款不支持退款"); if(r.idempotencyKey()!=null){ var existing=refundMapper.selectOne(new LambdaQueryWrapper<TransactionRefund>().eq(TransactionRefund::getTransactionId,id).eq(TransactionRefund::getIdempotencyKey,r.idempotencyKey())); if(existing!=null) return existing; } validateAmount(r.amountCents()); long total=refundMapper.selectList(new LambdaQueryWrapper<TransactionRefund>().eq(TransactionRefund::getTransactionId,id).eq(TransactionRefund::getStatus,"ACTIVE")).stream().mapToLong(TransactionRefund::getAmountCents).sum(); if(total+r.amountCents()>t.getAmountCents()) throw new BusinessException("REFUND_EXCEEDED","退款金额不能超过剩余可退款金额"); change(account(t.getAccountId(),"FUND"),t.getType().equals("EXPENSE")?r.amountCents():-r.amountCents()); TransactionRefund f=new TransactionRefund(); f.setTransactionId(id); f.setAmountCents(r.amountCents()); f.setRefundedAt(LocalDateTime.now()); f.setStatus("ACTIVE"); f.setIdempotencyKey(r.idempotencyKey()); f.setCreatedAt(LocalDateTime.now()); refundMapper.insert(f); return f; }
    @Transactional public void deleteRefund(long refundId) { TransactionRefund f=refundMapper.selectById(refundId); if(f==null||!f.getStatus().equals("ACTIVE")) throw new BusinessException("REFUND_NOT_FOUND","退款记录不存在"); LedgerTransaction t=require(f.getTransactionId()); change(account(t.getAccountId(),"FUND"),t.getType().equals("EXPENSE")?-f.getAmountCents():f.getAmountCents()); f.setStatus("DELETED"); AuditSupport.markDeleted(f); refundMapper.updateById(f); }
    @Transactional public LedgerTransaction repay(long creditId, RepaymentRequest r) { long id=bookId(); if(r.idempotencyKey()!=null){ var existing=transactionMapper.selectOne(new LambdaQueryWrapper<LedgerTransaction>().eq(LedgerTransaction::getBookId,id).eq(LedgerTransaction::getIdempotencyKey,r.idempotencyKey())); if(existing!=null) return existing; } validateAmount(r.amountCents()); if(r.fundAccountId()==null) throw new BusinessException("ACCOUNT_REQUIRED","请选择还款资金账户"); LedgerAccount credit=account(creditId,"CREDIT"), fund=account(r.fundAccountId(),"FUND"); if(credit.getBalanceCents()<r.amountCents()) throw new BusinessException("REPAYMENT_EXCEEDED","还款金额不能超过当前欠款"); change(fund,-r.amountCents()); change(credit,-r.amountCents()); LedgerTransaction t=new LedgerTransaction(); t.setBookId(id); t.setType("REPAYMENT"); t.setAmountCents(r.amountCents()); t.setAccountId(fund.getId()); t.setFromAccountId(fund.getId()); t.setToAccountId(credit.getId()); t.setOccurredAt(LocalDateTime.now()); t.setStatus("ACTIVE"); t.setIdempotencyKey(r.idempotencyKey()); t.setCreatedAt(LocalDateTime.now()); t.setUpdatedAt(LocalDateTime.now()); transactionMapper.insert(t); return t; }
    public HomeData home(YearMonth month) { List<LedgerTransaction> ts=list(month.atDay(1),month.atEndOfMonth(),null,null); long expense=0,income=0; for(LedgerTransaction t:ts){long effective=t.getAmountCents()-refundMapper.selectList(new LambdaQueryWrapper<TransactionRefund>().eq(TransactionRefund::getTransactionId,t.getId()).eq(TransactionRefund::getStatus,"ACTIVE")).stream().mapToLong(TransactionRefund::getAmountCents).sum(); if(t.getType().equals("EXPENSE"))expense+=effective; if(t.getType().equals("INCOME"))income+=effective;} YearMonth current=YearMonth.now(); int divisor=month.isBefore(current)?month.lengthOfMonth():month.equals(current)?LocalDate.now().getDayOfMonth():0; return new HomeData(expense,income,divisor==0?0:expense/divisor,ts); }
    public record HomeData(long expense,long income,long daily,List<LedgerTransaction> transactions) {}
}
