<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { request } from '../../utils/api'
import { useLedger } from '../../stores/ledger'
import { cents, yuan } from '../../utils/money'
const ledger=useLedger();const detail=ref<any>();const id=ref(0);const refundAmount=ref('');const loading=ref(true);const label=(t:string)=>({EXPENSE:'支出',INCOME:'收入',TRANSFER:'转账',REPAYMENT:'还款'}[t]||t)
async function load(){loading.value=true;try{detail.value=await request(`/api/app/transactions/${id.value}`)}finally{loading.value=false}}
onLoad(async q=>{id.value=Number(q?.id);try{await load()}catch{}})
function edit(){uni.navigateTo({url:`/pages/entry/entry?id=${id.value}`})}
async function refund(){try{const amount=cents(refundAmount.value||String((detail.value.effectiveCents/100).toFixed(2)));if(amount>detail.value.effectiveCents)throw new Error('退款金额不能超过剩余可退款金额');await request(`/api/app/transactions/${id.value}/refunds`,{method:'POST',data:{amountCents:amount,idempotencyKey:`refund-${id.value}-${Date.now()}`}});refundAmount.value='';uni.showToast({title:'退款成功，余额已刷新',icon:'success'});await load()}catch(e:any){uni.showToast({title:e.message||'退款失败，请重试',icon:'none'})}}
async function removeRefund(refundId:number){uni.showModal({title:'删除退款',content:'删除后会恢复这笔账单的有效金额，确定继续吗？',success:async r=>{if(r.confirm){try{await request(`/api/app/transactions/refunds/${refundId}`,{method:'DELETE'});await load()}catch{}}}})}
async function remove(){uni.showModal({title:'删除账单',content:'删除后会同步恢复账户余额，确定继续吗？',success:async r=>{if(r.confirm){try{await ledger.deleteTransaction(id.value);uni.navigateBack()}catch{}}}})}
</script>
<template><view class="page"><view class="topbar"><button class="back" aria-label="返回" @click="uni.navigateBack()">‹</button><text class="section-title" style="margin:0">账单详情</text><button v-if="detail && detail.transaction.type!=='REPAYMENT'" class="secondary-btn top-action" @click="edit">编辑</button></view><view v-if="loading" class="card empty">正在加载账单…</view><template v-if="detail"><view class="card" style="text-align:center"><text class="asset-sub">{{label(detail.transaction.type)}} · {{detail.effectiveCents===0?'已退款':detail.refundedCents?'部分退款':'正常'}}</text><text class="asset-number">{{yuan(detail.effectiveCents)}}</text><text class="asset-sub">{{detail.transaction.occurredAt.replace('T',' ')}}</text></view><view class="card"><view class="account-row"><text>原始金额</text><text>{{yuan(detail.transaction.amountCents)}}</text></view><view class="account-row" style="margin-top:14px"><text>账户</text><text>{{detail.transaction.accountId||detail.transaction.fromAccountId||'—'}}</text></view><view class="account-row" style="margin-top:14px"><text>备注</text><text>{{detail.transaction.note||'未填写'}}</text></view><view v-if="detail.refundedCents" class="account-row" style="margin-top:14px"><text>累计退款</text><text class="income">{{yuan(detail.refundedCents)}}</text></view><view v-for="refund in detail.refunds" :key="refund.id" class="account-row refund-row"><text class="asset-sub">退款 {{refund.refundedAt.replace('T',' ')}}</text><view><text class="income">{{yuan(refund.amountCents)}}</text><button class="link-btn" @click="removeRefund(refund.id)">删除</button></view></view></view><view v-if="['EXPENSE','INCOME'].includes(detail.transaction.type)" class="card"><label>本次退款金额（留空为全额）</label><input v-model="refundAmount" type="digit" placeholder="例如 12.50"/><button class="secondary-btn" :disabled="!detail.effectiveCents" @click="refund">{{detail.effectiveCents?'退款':'已全部退款'}}</button></view><view class="spacer"/><button class="danger-btn" @click="remove">删除账单</button></template></view></template>
<style scoped>.top-action{width:auto;padding:8px 12px}.refund-row{margin-top:10px}.link-btn{display:inline;padding:0 0 0 10px;background:transparent;color:#d47769;font-size:12px}</style>
