CREATE TABLE ha_todo_rule (
  id BIGINT NOT NULL COMMENT '待办规则ID',
  user_id BIGINT NOT NULL COMMENT '所属用户ID，与账本无关',
  title VARCHAR(100) NOT NULL COMMENT '待办标题',
  note VARCHAR(500) NULL COMMENT '待办备注',
  recurrence VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '重复规则：ONCE、DAILY、MONTHLY、EVERY_N_MONTHS、YEARLY',
  month_interval SMALLINT NOT NULL DEFAULT 1 COMMENT '间隔月数，EVERY_N_MONTHS时为2至120，其余为1',
  anchor_at DATETIME(3) NOT NULL COMMENT '首次计划时间，按北京时间解释',
  next_due_at DATETIME(3) NULL COMMENT '下一次尚未生成的计划时间，一次性规则为NULL',
  remind TINYINT NOT NULL DEFAULT 0 COMMENT '到期提醒：0关闭，1使用已配置通知渠道',
  active TINYINT NOT NULL DEFAULT 1 COMMENT '规则状态：0已结束，1继续生成',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  created_name VARCHAR(100) NULL COMMENT '创建人',
  updated_at DATETIME(3) NULL COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人ID',
  update_name VARCHAR(100) NULL COMMENT '更新人',
  deleted_at DATETIME(3) NULL COMMENT '删除时间',
  deleted_by BIGINT NULL COMMENT '删除人ID',
  deleted_name VARCHAR(100) NULL COMMENT '删除人',
  deleted TINYINT NULL DEFAULT 0 COMMENT '删除标识，0存在1删除',
  PRIMARY KEY (id), KEY idx_ha_todo_rule_user (user_id,deleted,active), KEY idx_ha_todo_rule_next (next_due_at,deleted,active),
  CONSTRAINT fk_ha_todo_rule_user FOREIGN KEY (user_id) REFERENCES app_user(id),
  CONSTRAINT ck_ha_todo_rule_deleted CHECK (deleted IS NULL OR deleted IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='哈待办独立重复规则表';

CREATE TABLE ha_todo_occurrence (
  id BIGINT NOT NULL COMMENT '待办发生项ID',
  rule_id BIGINT NOT NULL COMMENT '所属待办规则ID',
  user_id BIGINT NOT NULL COMMENT '所属用户ID，与账本无关',
  due_at DATETIME(3) NOT NULL COMMENT '本次计划时间，按北京时间解释',
  anchor_at DATETIME(3) NOT NULL COMMENT '本次重复规则首次时间快照',
  title VARCHAR(100) NOT NULL COMMENT '本次待办标题快照，规则修改后历史不变',
  note VARCHAR(500) NULL COMMENT '本次备注快照',
  recurrence VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '本次重复类型快照',
  month_interval SMALLINT NOT NULL COMMENT '本次间隔月数快照',
  remind TINYINT NOT NULL DEFAULT 0 COMMENT '本次到期提醒快照：0关闭1开启',
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '状态：PENDING待完成，COMPLETED已完成',
  completed_at DATETIME(3) NULL COMMENT '手动完成时间',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  created_name VARCHAR(100) NULL COMMENT '创建人',
  updated_at DATETIME(3) NULL COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人ID',
  update_name VARCHAR(100) NULL COMMENT '更新人',
  deleted_at DATETIME(3) NULL COMMENT '删除时间',
  deleted_by BIGINT NULL COMMENT '删除人ID',
  deleted_name VARCHAR(100) NULL COMMENT '删除人',
  deleted TINYINT NULL DEFAULT 0 COMMENT '删除标识，0存在1删除',
  PRIMARY KEY (id), KEY idx_ha_todo_occurrence_user (user_id,status,deleted,due_at), KEY idx_ha_todo_occurrence_rule (rule_id,deleted,status),
  CONSTRAINT fk_ha_todo_occurrence_rule FOREIGN KEY (rule_id) REFERENCES ha_todo_rule(id),
  CONSTRAINT fk_ha_todo_occurrence_user FOREIGN KEY (user_id) REFERENCES app_user(id),
  CONSTRAINT ck_ha_todo_occurrence_deleted CHECK (deleted IS NULL OR deleted IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='哈待办独立发生项与完成历史表';

CREATE TABLE ha_todo_delivery (
  id BIGINT NOT NULL COMMENT '待办提醒投递ID',
  occurrence_id BIGINT NOT NULL COMMENT '待办发生项ID',
  channel VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '通知渠道：BARK、PUSHPLUS',
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '投递状态：PENDING、SENDING、SENT、FAILED、SKIPPED',
  attempts SMALLINT NOT NULL DEFAULT 0 COMMENT '已尝试发送次数',
  next_attempt_at DATETIME(3) NOT NULL COMMENT '下一次尝试时间',
  locked_until DATETIME(3) NULL COMMENT '发送租约截止时间',
  sent_at DATETIME(3) NULL COMMENT '平台接受时间，不代表设备送达',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  created_name VARCHAR(100) NULL COMMENT '创建人',
  updated_at DATETIME(3) NULL COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人ID',
  update_name VARCHAR(100) NULL COMMENT '更新人',
  deleted_at DATETIME(3) NULL COMMENT '删除时间',
  deleted_by BIGINT NULL COMMENT '删除人ID',
  deleted_name VARCHAR(100) NULL COMMENT '删除人',
  deleted TINYINT NULL DEFAULT 0 COMMENT '删除标识，0存在1删除',
  PRIMARY KEY (id), UNIQUE KEY uk_ha_todo_delivery (occurrence_id,channel), KEY idx_ha_todo_delivery_retry (status,next_attempt_at,locked_until),
  CONSTRAINT fk_ha_todo_delivery_occurrence FOREIGN KEY (occurrence_id) REFERENCES ha_todo_occurrence(id),
  CONSTRAINT ck_ha_todo_delivery_deleted CHECK (deleted IS NULL OR deleted IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='哈待办提醒渠道投递状态表';

CREATE TABLE ha_todo_delivery_attempt (
  id BIGINT NOT NULL COMMENT '每次待办提醒发送尝试ID',
  delivery_id BIGINT NOT NULL COMMENT '所属渠道投递ID',
  occurrence_id BIGINT NOT NULL COMMENT '待办发生项ID',
  channel VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '实际发送渠道：BARK、PUSHPLUS',
  message_title VARCHAR(100) NOT NULL COMMENT '本次发送的消息标题，不含通知Key',
  message_body VARCHAR(600) NOT NULL COMMENT '本次发送的消息正文，不含通知Key',
  result VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '本次结果：SENDING发送中、ACCEPTED平台受理、FAILED失败、SKIPPED已完成或配置移除',
  attempted_at DATETIME(3) NOT NULL COMMENT '本次尝试时间',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  created_by BIGINT NULL COMMENT '创建人ID',
  created_name VARCHAR(100) NULL COMMENT '创建人',
  updated_at DATETIME(3) NULL COMMENT '更新时间',
  updated_by BIGINT NULL COMMENT '更新人ID',
  update_name VARCHAR(100) NULL COMMENT '更新人',
  deleted_at DATETIME(3) NULL COMMENT '删除时间',
  deleted_by BIGINT NULL COMMENT '删除人ID',
  deleted_name VARCHAR(100) NULL COMMENT '删除人',
  deleted TINYINT NULL DEFAULT 0 COMMENT '删除标识，0存在1删除',
  PRIMARY KEY (id), KEY idx_ha_todo_attempt_delivery (delivery_id,attempted_at), KEY idx_ha_todo_attempt_occurrence (occurrence_id,attempted_at),
  CONSTRAINT fk_ha_todo_attempt_delivery FOREIGN KEY (delivery_id) REFERENCES ha_todo_delivery(id),
  CONSTRAINT fk_ha_todo_attempt_occurrence FOREIGN KEY (occurrence_id) REFERENCES ha_todo_occurrence(id),
  CONSTRAINT ck_ha_todo_attempt_deleted CHECK (deleted IS NULL OR deleted IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='哈待办每次消息发送尝试与消息内容审计表';

CREATE TABLE ha_todo_request (
  user_id BIGINT NOT NULL COMMENT '所属用户ID',
  idempotency_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '写入请求幂等键，用户内唯一',
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '操作与请求参数的SHA256摘要',
  result_id BIGINT NULL COMMENT '本次操作返回的规则或发生项ID',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  deleted TINYINT NULL DEFAULT 0 COMMENT '删除标识，0存在1删除',
  PRIMARY KEY (user_id,idempotency_key),
  CONSTRAINT fk_ha_todo_request_user FOREIGN KEY (user_id) REFERENCES app_user(id),
  CONSTRAINT ck_ha_todo_request_deleted CHECK (deleted IS NULL OR deleted IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='哈待办写入幂等请求关系表';
