<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import BottomNav from '../../components/BottomNav.vue'
import { useLedger } from '../../stores/ledger'
import { yuan } from '../../utils/money'
const ledger=useLedger();const s=ledger.state;const cursor=ref(new Date());const selected=ref('');const month= computed(()=>`${cursor.value.getFullYear()}-${String(cursor.value.getMonth()+1).padStart(2,'0')}`);const selectedTransactions=computed(()=>s.transactions.filter(t=>!selected.value||t.occurredAt.slice(0,10)===selected.value));const daily=computed(()=>{let expense=0,income=0;for(const t of selectedTransactions.value){if(t.type==='EXPENSE')expense+=t.amountCents;if(t.type==='INCOME')income+=t.amountCents}return{expense,income,balance:income-expense}});const days=computed(()=>Array.from(new Set(s.transactions.map(t=>t.occurredAt.slice(0,10)))).sort());
async function load(){await ledger.refresh(month.value);if(!selected.value||!selected.value.startsWith(month.value))selected.value=days.value.at(-1)||''}onShow(()=>{if(s.token)load()});function move(delta:number){cursor.value=new Date(cursor.value.getFullYear(),cursor.value.getMonth()+delta,1);selected.value='';load()}function today(){cursor.value=new Date();selected.value='';load()}function open(id:number){uni.navigateTo({url:`/pages/detail/detail?id=${id}`})}
</script>
<template><view class="page"><view class="brand"><image src="/static/brand.png"/><view><text class="brand-name">按日期回看每一笔</text><text class="brand-sub">自然月账务记录</text></view></view><view class="card"><view class="topbar"><button class="secondary-btn small-action" aria-label="上个月" @click="move(-1)">‹</button><text class="section-title" style="margin:0">{{month.replace('-', ' 年 ')}} 月</text><view><button class="secondary-btn small-action" @click="today">今天</button><button class="secondary-btn small-action" aria-label="下个月" @click="move(1)">›</button></view></view><view class="calendar-days"><button v-for="day in days" :key="day" :class="{selected:selected===day}" @click="selected=day">{{day.slice(8)}}<text v-if="s.transactions.some(t=>t.occurredAt.slice(0,10)===day)">·</text></button></view><view class="asset-grid"><view class="small"><text class="asset-sub">当日支出</text><text class="expense">{{yuan(daily.expense)}}</text></view><view class="small"><text class="asset-sub">当日收入</text><text class="income">{{yuan(daily.income)}}</text></view><view class="small"><text class="asset-sub">当日结余</text><text>{{yuan(daily.balance)}}</text></view></view></view><text class="section-title">{{selected||'本月'}}账单</text><view v-if="!selectedTransactions.length" class="card empty">这一天还没有记账记录</view><button v-for="t in selectedTransactions" :key="t.id" class="transaction" @click="open(t.id)"><text class="transaction-icon">{{t.type==='INCOME'?'收':t.type==='EXPENSE'?'支':t.type==='TRANSFER'?'转':'还'}}</text><view class="transaction-copy"><text class="transaction-title">{{t.type}} · {{t.note||'无备注'}}</text><text class="transaction-note">{{t.occurredAt.replace('T',' ')}}</text></view><text class="transaction-amount">{{yuan(t.amountCents)}}</text><text class="arrow">›</text></button><BottomNav active="calendar"/></view></template>
<style scoped>.small-action{width:auto;padding:8px 12px;display:inline-block;margin:0 2px}.calendar-days{display:flex;gap:6px;overflow:auto;margin:8px 0 14px}.calendar-days button{min-width:44px;min-height:44px;border-radius:12px;background:#f2f6f4;color:#858b8b}.calendar-days button.selected{background:#278879;color:#fff}.calendar-days text{display:block}</style>
