<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { useLedger } from '../../stores/ledger'
import { request } from '../../utils/api'
import { cents, localDateTime } from '../../utils/money'

const ledger = useLedger(); const type = ref<'EXPENSE'|'INCOME'|'TRANSFER'>('EXPENSE'); const amount = ref(''); const note = ref(''); const accountIndex = ref(0); const toIndex = ref(1); const dateTime = ref(localDateTime()); const editingId = ref(0); const saving = ref(false)
const accounts = computed(() => ledger.state.accounts.filter(a => a.kind === 'FUND' && a.status === 'ACTIVE')); const isEdit = computed(() => editingId.value > 0); const typeLabel = (t:string) => t === 'EXPENSE' ? '支出' : t === 'INCOME' ? '收入' : '转账'; const operators = new Set(['+', '−', '×', '÷'])
function appendKey(key: string) { if (key === 'C') return void (amount.value = ''); if (key === '⌫') return void (amount.value = amount.value.slice(0, -1)); if (key === '=') return calculate(); const last = amount.value.slice(-1); if (operators.has(key) && (!amount.value || operators.has(last))) return; if (key === '.' && amount.value.split(/[+−×÷]/).pop()?.includes('.')) return; if (key === '.' && (!amount.value || operators.has(last))) amount.value += '0'; amount.value += key }
function calculate() { const expression = amount.value.replaceAll('−', '-').replaceAll('×', '*').replaceAll('÷', '/'); if (!/^\d+(\.\d{1,2})?([+\-*/]\d+(\.\d{1,2})?)*$/.test(expression)) throw new Error('算式有误，请检查后重试'); const values:number[]=[]; const ops:string[]=[]; let number=''; const apply=()=>{const b=values.pop()!;const a=values.pop()!;const op=ops.pop()!;if(op==='/'&&b===0)throw new Error('除数不能为 0，请重新输入');values.push(op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b)}; for(const ch of expression){if(/[\d.]/.test(ch))number+=ch;else{values.push(Number(number));number='';while(ops.length&&('*/'.includes(ops.at(-1)!)||'+-'.includes(ch)&&'+-'.includes(ops.at(-1)!)))apply();ops.push(ch)}} values.push(Number(number));while(ops.length)apply();const result=values[0];if(!Number.isFinite(result)||result<=0||result>999999999.99)throw new Error('金额必须在 ¥0.01～¥999,999,999.99 之间');amount.value=result.toFixed(2).replace(/\.00$/,'').replace(/(\.\d)0$/,'$1') }
async function loadForEdit(id:number) { await ledger.refresh(); const detail:any=await request(`/api/app/transactions/${id}`); const t=detail.transaction; if(!['EXPENSE','INCOME','TRANSFER'].includes(t.type)) throw new Error('还款流水不能从此处编辑'); editingId.value=id;type.value=t.type;amount.value=(t.amountCents/100).toFixed(2);note.value=t.note||'';dateTime.value=t.occurredAt.slice(0,16);const from=t.fromAccountId??t.accountId;accountIndex.value=Math.max(0,accounts.value.findIndex(a=>a.id===from));toIndex.value=Math.max(0,accounts.value.findIndex(a=>a.id===t.toAccountId)) }
onLoad(async (query) => { const id=Number(query?.id||0); try { if(id) await loadForEdit(id); else if(!ledger.state.accounts.length) await ledger.refresh() } catch(e:any) { uni.showToast({title:e.message||'加载失败，请重试',icon:'none'}) } })
async function save() { if(saving.value)return; saving.value=true; try { if(!amount.value)throw new Error('请输入大于 0 的金额'); if(/[+−×÷]/.test(amount.value))calculate(); const payload:any={type:type.value,amountCents:cents(amount.value),occurredAt:dateTime.value,note:note.value.trim()||undefined,idempotencyKey:isEdit.value?undefined:`app-${Date.now()}`}; if(type.value==='TRANSFER'){if(!accounts.value[accountIndex.value]||!accounts.value[toIndex.value])throw new Error('请先创建两个资金账户');if(accountIndex.value===toIndex.value)throw new Error('转出账户和转入账户不能相同');payload.fromAccountId=accounts.value[accountIndex.value].id;payload.toAccountId=accounts.value[toIndex.value].id}else{if(!accounts.value[accountIndex.value])throw new Error('请先创建资金账户');payload.accountId=accounts.value[accountIndex.value].id} if(isEdit.value)await ledger.updateTransaction(editingId.value,payload);else await ledger.createTransaction(payload);uni.showToast({title:isEdit.value?'账单已更新，余额已刷新':'记账成功，余额已刷新',icon:'success'});setTimeout(()=>uni.navigateBack(),400) } catch(e:any) {uni.showToast({title:e.message||'保存失败，请重试',icon:'none'})} finally{saving.value=false} }
</script>
<template><view class="page entry-page"><view class="topbar"><button class="back" aria-label="返回" @click="uni.navigateBack()">‹</button><text class="section-title" style="margin:0">{{isEdit?'编辑记账':'新增记账'}}</text><view style="width:40px"/></view><view class="segmented"><button v-for="t in ['EXPENSE','INCOME','TRANSFER']" :key="t" :class="{active:type===t}" @click="type=t as any">{{typeLabel(t)}}</button></view><view class="card"><input v-model="amount" class="amount-input" type="digit" placeholder="输入金额" maxlength="24"/><view class="keypad"><button v-for="key in ['7','8','9','÷','4','5','6','×','1','2','3','−','C','0','.','+']" :key="key" @click="appendKey(key)">{{key}}</button><button @click="appendKey('⌫')">⌫</button><button class="equals" @click="appendKey('=')">=</button></view><view class="field"><label>账户</label><picker v-if="type!=='TRANSFER'" mode="selector" :range="accounts.map(a=>a.name)" :value="accountIndex" @change="accountIndex=Number($event.detail.value)"><view class="account-row"><text>{{accounts[accountIndex]?.name||'选择资金账户'}}</text><text class="arrow">›</text></view></picker><view v-else><picker mode="selector" :range="accounts.map(a=>a.name)" :value="accountIndex" @change="accountIndex=Number($event.detail.value)"><view class="account-row"><text>转出：{{accounts[accountIndex]?.name||'选择账户'}}</text><text class="arrow">›</text></view></picker><picker mode="selector" :range="accounts.map(a=>a.name)" :value="toIndex" @change="toIndex=Number($event.detail.value)"><view class="account-row" style="margin-top:16px"><text>转入：{{accounts[toIndex]?.name||'选择账户'}}</text><text class="arrow">›</text></view></picker></view></view><view class="field"><label>日期与时间</label><input v-model="dateTime" type="datetime-local"/></view><view class="field"><label>备注（最多 100 字）</label><textarea v-model="note" maxlength="100" placeholder="写点什么吧"/></view></view><button class="primary-btn" :disabled="saving" @click="save">{{saving?'保存中…':'保存记账'}}</button></view></template>
<style scoped>.keypad{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:4px 0 16px}.keypad button{min-height:44px;border-radius:10px;background:#f2f6f4;color:#278879}.keypad .equals{background:#278879;color:#fff;grid-column:span 3}.primary-btn[disabled]{opacity:.6}</style>
